### ISSUE TITLE
[TTR-0003] Bug: Maximum health values bigger than 20 will produce an exception

### ISSUE THREAD

**Issue by PauMAVA** [PauMAVA/TheTowersRemastered#3]
* MC Version: 1.15.X
* Plugin Version: 1.0
Issue: maxhealth values bigger than 20 don't get applied and produce an exception.

Steps to reproduce:
      1. Set maxhealth to a value bigger than 20.
      2. Start a new game.

StackTrace:
```
[19:59:48] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[19:59:48] [Server thread/WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:59:48] [Server thread/WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:59:48] [Server thread/WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:59:48] [Server thread/WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[19:59:48] [Server thread/WARN]:        at me.PauMAVA.TTR.util.XPBarTimer.run(XPBarTimer.java:57)
[19:59:48] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81)
[19:59:48] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394)
[19:59:48] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036)
[19:59:48] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:399)
[19:59:48] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984)
[19:59:48] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824)
[19:59:48] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[19:59:48] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: Health must be between 0 and 20.0(30.0)
[19:59:48] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:108)
[19:59:48] [Server thread/WARN]:        at me.PauMAVA.TTR.match.TTRMatch.startMatch(TTRMatch.java:72)
[19:59:48] [Server thread/WARN]:        ... 12 more
```

**Comment by PauMAVA** [comment]
Fixed on 922b9ae.
