### ISSUE TITLE
[TRR-0004] There is an error

### ISSUE THREAD

**Issue by RIPISDRAD** [PauMAVA/TheTowersRemastered#4]
This is my whole damn console so plz help
```
C:\Users\Administrator\Desktop\sv shakh bara hame mini game ha>java -Xmx5G -jar -DIReallyKnowWhatIAmDoingISwear paper-1.16.5-573.jar nogui
System Info: Java 16 (Java HotSpot(TM) 64-Bit Server VM 16.0.1+9-24) Host: Windows Server 2019 10.0 (amd64)
Loading libraries, please wait...
[21:03:13 ERROR]: No key layers in MapLike[{}]; No key structures in MapLike[{}]; Not a registry ops
[21:03:14 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[21:03:15 INFO]: Reloading ResourceManager: Default, bukkit
[21:03:16 INFO]: Loaded 7 recipes
[21:03:18 INFO]: Starting minecraft server version 1.16.5
[21:03:18 INFO]: Loading properties
[21:03:18 INFO]: This server is running Paper version git-Paper-573 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[21:03:19 INFO]: Debug logging is disabled
[21:03:19 INFO]: Server Ping Player Sample Count: 12
[21:03:19 INFO]: Using 4 threads for Netty based IO
[21:03:19 INFO]: Default game type: SURVIVAL
[21:03:19 INFO]: Generating keypair
[21:03:19 INFO]: Starting Minecraft server on localhost:25563
[21:03:19 INFO]: Using default channel type
[21:03:20 WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[21:03:26 WARN]: Legacy plugin WorldEdit v6.1.9;caf0ad9 does not specify an api-version.
[21:03:26 INFO]: [TheBridge] Loading TheBridge v1.1.1
[21:03:26 INFO]: [AdvancedMLGRush] Loading AdvancedMLGRush v2.3.2
[21:03:26 INFO]: [WorldEdit] Loading WorldEdit v6.1.9;caf0ad9
[21:03:26 INFO]: [BuildBattle] Loading BuildBattle v4.5.0
[21:03:26 INFO]: [TNTRun_reloaded] Loading TNTRun_reloaded v9.10.0
[21:03:26 INFO]: [StickFight] Loading StickFight v1.6
[21:03:26 INFO]: [ThirdLife] Loading ThirdLife v1.4
[21:03:26 INFO]: [VoidGenerator] Loading VoidGenerator v1.7.0
[21:03:26 INFO]: [TheTowersRemastered] Loading TheTowersRemastered v1.1
[21:03:26 INFO]: [Thimble] Loading Thimble v1.2.0
[21:03:26 INFO]: [KuffleItems] Loading KuffleItems v1.3
[21:03:26 INFO]: [Multiverse-Core] Loading Multiverse-Core v4.2.2-b812
[21:03:26 INFO]: Server permissions file permissions.yml is empty, ignoring it
[21:03:26 INFO]: [VoidGenerator] Enabling VoidGenerator v1.7.0
[21:03:26 INFO]: [VoidGenerator] v1_15
[21:03:26 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[21:03:26 WARN]: The server will make no attempt to authenticate usernames. Beware.
[21:03:26 WARN]: Whilst this makes it possible to use BungeeCord, unless access to your server is properly restricted, it also opens up the ability for hackers to connect with any username they choose.
[21:03:26 WARN]: Please see http://www.spigotmc.org/wiki/firewall-guide/ for further information.
[21:03:26 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[21:03:26 INFO]: Preparing level "TTR"
[21:03:26 INFO]: Preparing start region for dimension minecraft:overworld
[21:03:27 INFO]: Loaded 0 spawn chunks for world TTR
[21:03:27 INFO]: Preparing spawn area: 0%
[21:03:27 INFO]: Time elapsed: 481 ms
[21:03:27 INFO]: [TheBridge] Enabling TheBridge v1.1.1
[21:03:27 INFO]: [TheBridge] Connecting to services, please wait! Server may freeze a bit!
[21:03:28 INFO]: [TheBridge] Hooked with ServiceRegistry! Initialized services properly!
[21:03:28 INFO]: [TheBridge] Fetched latest localization file from repository.
[21:03:29 INFO]: [The Bridge] Loaded locale English (English ID: en_GB) by Tigerpanzer_02
[21:03:29 INFO]: [The Bridge] Locale en_GB is latest! Awesome!
[21:03:29 INFO]: [TheBridge] -_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_-
[21:03:29 INFO]: [TheBridge]
[21:03:29 INFO]: [TheBridge] Versions:
[21:03:29 INFO]: [TheBridge] Plugin: 1.1.1 | Server: git-Paper-573 (MC: 1.16.5) | Detected: v1_16_R3 | Software: Paper | Java: 16.0.1
[21:03:29 INFO]: [TheBridge]
[21:03:29 INFO]: [TheBridge] This plugin was created by Plugily Projects as part of an open source project ( https://donate.plugily.xyz )
[21:03:29 INFO]: [TheBridge]
[21:03:29 INFO]: [TheBridge][SUPPORT] If you have any problems, you can always contact us on our Discord server! ( https://discord.plugily.xyz )
[21:03:29 INFO]: [TheBridge][SUPPORT] You can also check out our wiki at https://wiki.plugily.xyz
[21:03:29 INFO]: [TheBridge]
[21:03:29 INFO]: [TheBridge]                               The plugin got fully enabled! Enjoy the plugin ;)
[21:03:29 INFO]: [TheBridge] -_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_-
[21:03:29 INFO]: [AdvancedMLGRush] Enabling AdvancedMLGRush v2.3.2
[21:03:29 INFO]: [AdvancedMLGRush] Detected server version: 1.16.5-R0.1-SNAPSHOT
[21:03:29 INFO]: [AdvancedMLGRush] Loaded Language: English
[21:03:29 INFO]: Preparing start region for dimension minecraft:test
[21:03:30 INFO]: Loaded 0 spawn chunks for world test
[21:03:30 INFO]: Preparing spawn area: 0%
[21:03:30 INFO]: Preparing spawn area: 0%
[21:03:30 INFO]: Time elapsed: 564 ms
[21:03:30 INFO]: Preparing start region for dimension minecraft:mlgrush-templates
[21:03:30 INFO]: Loaded 0 spawn chunks for world mlgRush-templates
[21:03:30 INFO]: Preparing spawn area: 0%
[21:03:30 INFO]: Time elapsed: 95 ms
[21:03:31 INFO]: [WorldEdit] Enabling WorldEdit v6.1.9;caf0ad9*
[21:03:32 INFO]: WEPIF: Using the Bukkit Permissions API.
[21:03:32 ERROR]: Error occurred while enabling WorldEdit v6.1.9;caf0ad9 (Is it up to date?)
java.lang.IllegalArgumentException: Channel must contain : separator (attempted to use WECUI)
        at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:503) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.plugin.messaging.StandardMessenger.registerIncomingPluginChannel(StandardMessenger.java:216) ~[patched_1.16.5.jar:git-Paper-573]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:110) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:580) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-573]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[21:03:32 INFO]: [WorldEdit] Disabling WorldEdit v6.1.9;caf0ad9
[21:03:32 INFO]: [BuildBattle] Enabling BuildBattle v4.5.0
[21:03:32 INFO]: [BuildBattle] Connecting to services, please wait! Server may freeze a bit!
[21:03:32 INFO]: [BuildBattle] Hooked with ServiceRegistry! Initialized services properly!
[21:03:33 INFO]: [BuildBattle] Fetched latest localization file from repository.
[21:03:33 INFO]: [BuildBattle] Loaded locale English (English ID: en_GB) by Plajer
[21:03:33 INFO]: [BuildBattle] Locale en_GB is latest! Awesome!
[21:03:34 INFO]: [BuildBattle] -_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_-
[21:03:34 INFO]: [BuildBattle]
[21:03:34 INFO]: [BuildBattle] Versions:
[21:03:34 INFO]: [BuildBattle] Plugin: 4.5.0 | Server: git-Paper-573 (MC: 1.16.5) | Detected: v1_16_R3 | Software: Paper | Java: 16.0.1
[21:03:34 INFO]: [BuildBattle]
[21:03:34 INFO]: [BuildBattle] This plugin was created by Plugily Projects as part of an open source project ( https://donate.plugily.xyz )
[21:03:34 INFO]: [BuildBattle]
[21:03:34 INFO]: [BuildBattle][SUPPORT] If you have any problems, you can always contact us on our Discord server! ( https://discord.plugily.xyz )
[21:03:34 INFO]: [BuildBattle][SUPPORT] You can also check out our wiki at https://wiki.plugily.xyz
[21:03:34 INFO]: [BuildBattle]
[21:03:34 INFO]: [BuildBattle]                               The plugin got fully enabled! Enjoy the plugin ;)
[21:03:34 INFO]: [BuildBattle] -_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_--_-_-_-
[21:03:34 INFO]: [TNTRun_reloaded] Enabling TNTRun_reloaded v9.10.0
[21:03:34 ERROR]: Error occurred while enabling TNTRun_reloaded v9.10.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/IncompleteRegionException
        at tntrun.selectionget.PlayerSelection.<init>(PlayerSelection.java:34) ~[?:?]
        at tntrun.commands.setup.SetupCommandsHandler.<init>(SetupCommandsHandler.java:80) ~[?:?]
        at tntrun.TNTRun.setupPlugin(TNTRun.java:265) ~[?:?]
        at tntrun.TNTRun.onEnable(TNTRun.java:108) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:580) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-573]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.IncompleteRegionException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:433) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-573]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 14 more
[21:03:34 INFO]: [TNTRun_reloaded] Disabling TNTRun_reloaded v9.10.0
[21:03:34 ERROR]: Error occurred while disabling TNTRun_reloaded v9.10.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "tntrun.MySQL.close()" because "this.mysql" is null
        at tntrun.TNTRun.onDisable(TNTRun.java:142) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:580) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-573]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[21:03:34 INFO]: [StickFight] Enabling StickFight v1.6
[21:03:34 INFO]: [StickFight][INFO] Das Stickfight Plugin ist aktiviert.
[21:03:34 INFO]: [ThirdLife] Enabling ThirdLife v1.4
[21:03:34 INFO]: [ThirdLife] ThirdLife [Online]
[21:03:34 INFO]: [ThirdLife] PlaceHolderAPI not detected, some ThirdLife plugin features will not be available
[21:03:34 INFO]: [TheTowersRemastered] Enabling TheTowersRemastered v1.1
[21:03:34 ERROR]: Error occurred while enabling TheTowersRemastered v1.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R1/Packet
        at me.PauMAVA.TTR.TTRCore.onEnable(TTRCore.java:57) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:580) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-573]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_16_R1.Packet
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:116) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-573]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 11 more
[21:03:34 INFO]: [TheTowersRemastered] Disabling TheTowersRemastered v1.1
[21:03:34 INFO]: [Thimble] Enabling Thimble v1.2.0
[21:03:35 INFO]: [KuffleItems] Enabling KuffleItems v1.3
[21:03:35 INFO]: [KuffleItems] Load ages.json from Resource
[21:03:35 INFO]: [KuffleItems] Load items_1.16.json from Resource
[21:03:35 INFO]: [KuffleItems] Load rewards_1.16.json from Resource
[21:03:35 INFO]: [KuffleItems] Load items_lang.json from Resource
[21:03:36 INFO]: [KuffleItems] Add 28 Custom Crafts.
[21:03:36 INFO]: [KuffleItems] Add 3 Game Listeners.
[21:03:36 INFO]: [KuffleItems] Add 24 Plugin Commands.
[21:03:36 INFO]: [KuffleItems] Add 11 Plugin Tab Completer.
[21:03:36 INFO]: [KuffleItems] Plugin turned ON.
[21:03:36 INFO]: [Multiverse-Core] Enabling Multiverse-Core v4.2.2-b812
[21:03:36 WARN]: [Multiverse-Core] "Multiverse-Core v4.2.2-b812" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].
[21:03:36 INFO]: [Multiverse-Core] We are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore.
[21:03:36 INFO]: [Multiverse-Core] Loading World & Settings - 'TTR' - Env: NORMAL - Type: FLAT & seed: 0
[21:03:36 INFO]: Preparing start region for dimension minecraft:world
[21:03:37 INFO]: Loaded 0 spawn chunks for world world
[21:03:37 INFO]: Preparing spawn area: 0%
[21:03:37 INFO]: Preparing spawn area: 0%
[21:03:37 INFO]: Preparing spawn area: 16%
[21:03:38 INFO]: Time elapsed: 1118 ms
[21:03:38 ERROR]: [VoidGenerator] The BiomeID: "<biome>" is invalid. The biome defaulted to "THE_VOID".
[21:03:38 INFO]: Preparing start region for dimension minecraft:ki
[21:03:38 INFO]: Loaded 0 spawn chunks for world ki
[21:03:38 INFO]: Preparing spawn area: 0%
[21:03:38 INFO]: Time elapsed: 112 ms
[21:03:38 INFO]: [Multiverse-Core] 5 - World(s) loaded.
[21:03:38 WARN]: [Multiverse-Core] Buscript failed to load! The script command will be disabled!
[21:03:38 INFO]: [Multiverse-Core] Version 4.2.2-b812 (API v24) Enabled - By dumptruckman, Rigby, fernferret, lithium3141 and main--
[21:03:38 INFO]: Running delayed init tasks
[21:03:38 INFO]: [StickFight][INFO] Loading Game:
[21:03:38 INFO]: [StickFight][INFO]  - 1
[21:03:38 INFO]: [StickFight][INFO] GamesLoaded!
[21:03:38 INFO]: Done (19.757s)! For help, type "help"
[21:03:38 INFO]: Timings Reset
[21:03:39 INFO]: [AdvancedMLGRush] Loaded 0 Map-Template
[21:03:56 INFO]: UUID of player RIPISDEAD is 49aae35a-da22-3f62-b377-e8cd16dddae7
[21:03:56 INFO]: RIPISDEAD[/95.162.154.236:52251] logged in with entity id 243 at ([TTR]0.5, 208.0, 1014.5)
[21:03:57 INFO]: UUID of player biasab is 351093f3-35e0-3bed-82ce-391d11dee9a1
[21:03:57 WARN]: java.lang.NullPointerException: Cannot read field "id" because "data" is null
[21:03:57 WARN]:        at de.febanhd.mlgrush.util.UUIDFetcher.getUUIDAt(UUIDFetcher.java:89)
[21:03:57 WARN]:        at de.febanhd.mlgrush.util.UUIDFetcher.getUUID(UUIDFetcher.java:58)
[21:03:57 WARN]:        at de.febanhd.mlgrush.game.lobby.inventorysorting.InventorySortingDataHandler.hasSorting(InventorySortingDataHandler.java:100)
[21:03:57 WARN]:        at de.febanhd.mlgrush.game.lobby.inventorysorting.InventorySortingCach.lambda$loadSorting$0(InventorySortingCach.java:16)
[21:03:57 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:03:57 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[21:03:57 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[21:03:57 WARN]: java.lang.NullPointerException: Cannot read field "id" because "data" is null
[21:03:57 WARN]:        at de.febanhd.mlgrush.util.UUIDFetcher.getUUIDAt(UUIDFetcher.java:89)
[21:03:57 WARN]:        at de.febanhd.mlgrush.util.UUIDFetcher.getUUID(UUIDFetcher.java:58)
[21:03:57 WARN]:        at de.febanhd.mlgrush.util.UUIDFetcher.lambda$getUUID$0(UUIDFetcher.java:48)
[21:03:57 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:03:57 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[21:03:57 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[21:03:57 WARN]: Exception in thread "pool-13-thread-1" java.lang.NullPointerException: Cannot invoke "java.util.UUID.toString()" because "uuid" is null
[21:03:57 WARN]:        at de.febanhd.mlgrush.stats.StatsDataHandler.hasStats(StatsDataHandler.java:85)
[21:03:57 WARN]:        at de.febanhd.mlgrush.stats.StatsCach.lambda$loadStats$0(StatsCach.java:18)
[21:03:57 WARN]:        at de.febanhd.mlgrush.util.UUIDFetcher.lambda$getUUID$0(UUIDFetcher.java:48)
[21:03:57 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:03:57 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[21:03:57 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[21:03:57 WARN]: Exception in thread "pool-6-thread-2" java.lang.NullPointerException: Cannot invoke "java.util.UUID.toString()" because the return value of "de.febanhd.mlgrush.util.UUIDFetcher.getUUID(String)" is null
[21:03:57 WARN]:        at de.febanhd.mlgrush.game.lobby.inventorysorting.InventorySortingDataHandler.hasSorting(InventorySortingDataHandler.java:100)
[21:03:57 WARN]:        at de.febanhd.mlgrush.game.lobby.inventorysorting.InventorySortingCach.lambda$loadSorting$0(InventorySortingCach.java:16)
[21:03:57 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:03:57 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[21:03:57 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[21:03:57 INFO]: biasab[/95.162.154.236:52252] logged in with entity id 244 at ([TTR]0.5, 208.0, 1014.5)
[21:04:39 INFO]: RIPISDEAD issued server command: /mvtp TTR
[21:05:00 INFO]: RIPISDEAD issued server command: /ttrstart
[21:05:00 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'ttrstart' in plugin TheTowersRemastered v1.1 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2168) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1983) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1936) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1206) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-573]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[21:05:07 INFO]: RIPISDEAD issued server command: /ttrenable
[21:05:07 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'ttrenable' in plugin TheTowersRemastered v1.1 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2168) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1983) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1936) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-573]
```

**Comment by PauMAVA** [comment]
Hello! It seems that you are using a `1.16.3` Paper server while having version `1.1` of this plugin. Version `1.1` of this plugin is compatible only with `1.15.X` server versions. 

Please go to [the release page](https://github.com/PauMAVA/TheTowersRemastered/releases/tag/1.2) and download version `1.2` for Minecraft `1.16.X` (the name of the file is ` TheTowersRemastered.16-1.2.jar`) and replace your current `.jar` with it. The rest of the errors are unrelated to this plugin (they point to your `WorldEdit` not loading correctly).

**Comment by RIPISDRAD** [comment]
Tnx man helped a lot
