### ISSUE TITLE
[TTR-0005] ClassNotFoundException net.minecraft.server.v1_16_R1.Packet

### ISSUE THREAD

**Issue by RIPISDRAD** [PauMAVA/TheTowersRemastered#5]
```
C:\Users\Administrator\Desktop\rip sv\build 3 failed>java -Xmx5G -jar -DIReallyKnowWhatIAmDoingISwear paper-1.16.5-573.jar nogui
System Info: Java 16 (Java HotSpot(TM) 64-Bit Server VM 16.0.1+9-24) Host: Windows Server 2019 10.0 (amd64)
Loading libraries, please wait...
[18:47:29 ERROR]: No key layers in MapLike[{}]; No key structures in MapLike[{}]; Not a registry ops
[18:47:29 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18:47:30 INFO]: Reloading ResourceManager: Default, bukkit
[18:47:31 INFO]: Loaded 7 recipes
[18:47:33 INFO]: Starting minecraft server version 1.16.5
[18:47:33 INFO]: Loading properties
[18:47:33 INFO]: This server is running Paper version git-Paper-573 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[18:47:33 INFO]: Debug logging is disabled
[18:47:33 INFO]: Server Ping Player Sample Count: 12
[18:47:33 INFO]: Using 4 threads for Netty based IO
[18:47:33 INFO]: Default game type: SURVIVAL
[18:47:33 INFO]: Generating keypair
[18:47:33 INFO]: Starting Minecraft server on localhost:25563
[18:47:33 INFO]: Using default channel type
[18:47:34 INFO]: [WorldEdit] Loading WorldEdit v7.2.5+57d5ac9
[18:47:35 INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@4d71ca45]
[18:47:35 INFO]: [VoidGenerator] Loading VoidGenerator v1.7.0
[18:47:35 INFO]: [TheTowersRemastered] Loading TheTowersRemastered v1.1
[18:47:35 INFO]: [Multiverse-Core] Loading Multiverse-Core v4.2.2-b812
[18:47:35 INFO]: Server permissions file permissions.yml is empty, ignoring it
[18:47:35 INFO]: [WorldEdit] Enabling WorldEdit v7.2.5+57d5ac9
[18:47:35 INFO]: WEPIF: Using the Bukkit Permissions API.
[18:47:35 INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_16_R3 as the Bukkit adapter
[18:47:37 INFO]: [VoidGenerator] Enabling VoidGenerator v1.7.0
[18:47:37 INFO]: [VoidGenerator] v1_15
[18:47:37 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[18:47:37 WARN]: The server will make no attempt to authenticate usernames. Beware.
[18:47:37 WARN]: Whilst this makes it possible to use BungeeCord, unless access to your server is properly restricted, it also opens up the ability for hackers to connect with any username they choose.
[18:47:37 WARN]: Please see http://www.spigotmc.org/wiki/firewall-guide/ for further information.
[18:47:37 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[18:47:37 INFO]: Preparing level "TTR"
[18:47:38 INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[18:47:38 INFO]: Preparing start region for dimension minecraft:overworld
[18:47:39 INFO]: Loaded 0 spawn chunks for world TTR
[18:47:39 INFO]: Preparing spawn area: 0%
[18:47:39 INFO]: Preparing spawn area: 9%
[18:47:39 INFO]: Time elapsed: 539 ms
[18:47:39 INFO]: Preparing start region for dimension minecraft:the_nether
[18:47:39 INFO]: Loaded 0 spawn chunks for world TTR_nether
[18:47:39 INFO]: Preparing spawn area: 0%
[18:47:39 INFO]: Time elapsed: 197 ms
[18:47:39 INFO]: Preparing start region for dimension minecraft:the_end
[18:47:39 INFO]: Loaded 0 spawn chunks for world TTR_the_end
[18:47:39 INFO]: Time elapsed: 270 ms
[18:47:39 INFO]: [TheTowersRemastered] Enabling TheTowersRemastered v1.1
[18:47:39 ERROR]: Error occurred while enabling TheTowersRemastered v1.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R1/Packet
        at me.PauMAVA.TTR.TTRCore.onEnable(TTRCore.java:57) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:580) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[patched_1.16.5.jar:git-Paper-573]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-573]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_16_R1.Packet
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:116) ~[patched_1.16.5.jar:git-Paper-573]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-573]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 11 more
[18:47:39 INFO]: [TheTowersRemastered] Disabling TheTowersRemastered v1.1
[18:47:39 INFO]: [Multiverse-Core] Enabling Multiverse-Core v4.2.2-b812
[18:47:39 WARN]: [Multiverse-Core] "Multiverse-Core v4.2.2-b812" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].
[18:47:39 INFO]: [Multiverse-Core] We are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore.
[18:47:39 WARN]: [Multiverse-Core] WorldManager: Can't load this world because the folder was deleted/moved: world
[18:47:39 WARN]: [Multiverse-Core] Use '/mv remove' to remove it from the config!
[18:47:39 WARN]: [Multiverse-Core] WorldManager: Can't load this world because the folder was deleted/moved: world_the_end
[18:47:39 WARN]: [Multiverse-Core] Use '/mv remove' to remove it from the config!
[18:47:39 WARN]: [Multiverse-Core] WorldManager: Can't load this world because the folder was deleted/moved: world_nether
[18:47:39 WARN]: [Multiverse-Core] Use '/mv remove' to remove it from the config!
[18:47:39 WARN]: [Multiverse-Core] WorldManager: Can't load this world because the folder was deleted/moved: world1
[18:47:39 WARN]: [Multiverse-Core] Use '/mv remove' to remove it from the config!
[18:47:39 INFO]: [Multiverse-Core] 3 - World(s) loaded.
[18:47:39 WARN]: [Multiverse-Core] Buscript failed to load! The script command will be disabled!
[18:47:39 INFO]: [Multiverse-Core] Version 4.2.2-b812 (API v24) Enabled - By dumptruckman, Rigby, fernferret, lithium3141 and main--
[18:47:40 INFO]: Running delayed init tasks
[18:47:40 INFO]: Done (7.044s)! For help, type "help"
[18:47:40 INFO]: Timings Reset
```

This happens after enabling
![Capture](https://user-images.githubusercontent.com/76468672/118668440-1d8e9780-b80a-11eb-8464-b818bdcb1009.PNG)
This is all my plugins and if you need something else say it

**Comment by PauMAVA** [comment]
Hello. I will take a look at it tonight.

**Comment by PauMAVA** [comment]
I am not able to reproduce your error. I am using a `PaperMC 1.16.5 build 573`, the same that appears in your logs. I have also downloaded the following plugins and versions:
* WorldEdit 7.2.5
* Multiverse-Core 4.2.2
* VoidGenerator 1.7.0

The server is just loading fine:
```
*** Warning, you've not updated in a while! ***
*** Please download a new build as per instructions from https://papermc.io/downloads ***
System Info: Java 11 (OpenJDK 64-Bit Server VM 11+28) Host: Windows 10 10.0 (amd64)
Loading libraries, please wait...
[21:58:17 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[21:58:17 INFO]: Reloading ResourceManager: Default, bukkit
[21:58:18 INFO]: Loaded 7 recipes
[21:58:19 INFO]: Starting minecraft server version 1.16.5
[21:58:19 INFO]: Loading properties
[21:58:19 INFO]: This server is running Paper version git-Paper-573 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[21:58:19 INFO]: Debug logging is disabled
[21:58:19 INFO]: Using 4 threads for Netty based IO
[21:58:19 INFO]: Server Ping Player Sample Count: 12
[21:58:19 INFO]: Default game type: SURVIVAL
[21:58:19 INFO]: Generating keypair
[21:58:19 INFO]: Starting Minecraft server on *:25565
[21:58:19 INFO]: Using default channel type
[21:58:20 INFO]: [WorldEdit] Loading WorldEdit v7.2.5+57d5ac9
[21:58:21 INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@726edf82]
[21:58:21 INFO]: [VoidGenerator] Loading VoidGenerator v1.7.0
[21:58:21 INFO]: [TheTowersRemastered] Loading TheTowersRemastered v1.1
[21:58:21 INFO]: [Multiverse-Core] Loading Multiverse-Core v4.2.2-b812
[21:58:21 INFO]: Server permissions file permissions.yml is empty, ignoring it
[21:58:21 INFO]: [WorldEdit] Enabling WorldEdit v7.2.5+57d5ac9
[21:58:21 INFO]: WEPIF: Updated config file
[21:58:21 INFO]: WEPIF: Using the Bukkit Permissions API.
[21:58:21 INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_16_R3 as the Bukkit adapter
[21:58:21 INFO]: [WorldEdit] Default configuration file written: config.yml
[21:58:22 INFO]: [VoidGenerator] Enabling VoidGenerator v1.7.0
[21:58:22 INFO]: [VoidGenerator] v1_15
[21:58:22 INFO]: [VoidGenerator] The file:"configuration.json"was not found.
[21:58:22 INFO]: [VoidGenerator] A new file will be generated and the default configuration will be used instead.
[21:58:22 INFO]: Preparing level "world"
[21:58:22 INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[21:58:22 INFO]: Preparing start region for dimension minecraft:overworld
[21:58:22 INFO]: Loaded 0 spawn chunks for world world
[21:58:22 INFO]: Preparing spawn area: 0%
[21:58:22 INFO]: Time elapsed: 217 ms
[21:58:22 INFO]: Preparing start region for dimension minecraft:the_nether
[21:58:23 INFO]: Loaded 0 spawn chunks for world world_nether
[21:58:23 INFO]: Time elapsed: 145 ms
[21:58:23 INFO]: Preparing start region for dimension minecraft:the_end
[21:58:23 INFO]: Loaded 0 spawn chunks for world world_the_end
[21:58:23 INFO]: Time elapsed: 70 ms
[21:58:23 INFO]: [TheTowersRemastered] Enabling TheTowersRemastered v1.1
[21:58:23 WARN]: [TheTowersRemastered] TTR is disabled on server start. Use /ttrenable to enable it on start. Make sure to be using the desired map.
[21:58:23 INFO]: [Multiverse-Core] Enabling Multiverse-Core v4.2.2-b812
[21:58:23 WARN]: [Multiverse-Core] "Multiverse-Core v4.2.2-b812" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].
[21:58:23 INFO]: [Multiverse-Core] We are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore.
[21:58:23 WARN]: [Multiverse-Core] Cannot load worlds.yml
[21:58:23 INFO]: [Multiverse-Core] Loading World & Settings - 'world' - Env: NORMAL - Type: NORMAL & seed: 5038553182997349445
[21:58:23 INFO]: [Multiverse-Core] Loading World & Settings - 'world_nether' - Env: NETHER - Type: NORMAL & seed: 5038553182997349445
[21:58:23 INFO]: [Multiverse-Core] Loading World & Settings - 'world_the_end' - Env: THE_END - Type: NORMAL & seed: 5038553182997349445
[21:58:24 INFO]: [Multiverse-Core] 3 - World(s) loaded.
[21:58:24 WARN]: Warning: Nashorn engine is planned to be removed from a future JDK release
[21:58:24 INFO]: [Multiverse-Core] Version 4.2.2-b812 (API v24) Enabled - By dumptruckman, Rigby, fernferret, lithium3141 and main--
[21:58:24 INFO]: Running delayed init tasks
[21:58:24 INFO]: Done (5.276s)! For help, type "help"
```
![imagen](https://user-images.githubusercontent.com/36012050/119044834-fb884700-b9ba-11eb-82f2-a9dec0b37acc.png)
![imagen](https://user-images.githubusercontent.com/36012050/119044859-0216be80-b9bb-11eb-9739-ddf690524c00.png)
I don't know what is causing the `ClassNotFoundException`. I recommend that you update PAPERMC to its latest build (706) and check if the problem persists.

**Comment by PauMAVA** [comment]
Closing due to inactivity.

**Comment by PauMAVA** [comment]
Hello,

I was finally able to reproduce and fix this issue. You may use version `1.2.1` of this plugin.

[Version 1.2.1](https://github.com/PauMAVA/TheTowersRemastered/releases/tag/v1.2.1)

**Comment by RIPISDRAD** [comment]
Yeay thanks man look forward for making great maps for it
